[package]
name = "covert_tcp"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]

[dependencies]
pnet = "0.21.0"
pnet_packet = "0.21.0"
pnet_transport = "0.21.0"
docopt = "1.0.2"
serde = "1.0.80"
serde_derive = "1.0.80"
log = "0.4.6"
env_logger = "0.5.13"